### ISSUE TITLE
[BUG] Does not seem to work with on premise git enterprise

### ISSUE THREAD

**Issue by protux** [apoclyps/reviews#137]
**Describe the bug**
When reviews tries to connect to the API of an on premise git instance it fails with the following stack trace:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/reviews/__main__.py", line 7, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/reviews/cli/main.py", line 40, in main
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/reviews/cli/main.py", line 33, in dashboard
    render()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/reviews/tasks.py", line 120, in render
    body=_render_pull_requests(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/reviews/tasks.py", line 38, in _render_pull_requests
    tables = [
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/reviews/tasks.py", line 39, in <listcomp>
    controller.retrieve_pull_requests(org=org, repository=repo)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/reviews/controller.py", line 21, in retrieve_pull_requests
    pull_requests = self.update_pull_requests(org=org, repository=repository)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/reviews/controller.py", line 48, in update_pull_requests
    pull_requests = self.client.get_pull_requests(org=org, repo=repository)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/reviews/source_control/client.py", line 35, in get_pull_requests
    return self._get_pull_requests(repository=repository)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/reviews/source_control/client.py", line 30, in _get_pull_requests
    return list(repository.get_pulls(state=state, sort=sort))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github/PaginatedList.py", line 56, in __iter__
    newElements = self._grow()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github/PaginatedList.py", line 67, in _grow
    newElements = self._fetchNextPage()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github/PaginatedList.py", line 199, in _fetchNextPage
    headers, data = self.__requester.requestJsonAndCheck(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github/Requester.py", line 354, in requestJsonAndCheck
    *self.requestJson(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github/Requester.py", line 454, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github/Requester.py", line 519, in __requestEncode
    url = self.__makeAbsoluteUrl(url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github/Requester.py", line 591, in __makeAbsoluteUrl
    assert o.hostname in [
AssertionError: None
```

**To Reproduce**
Steps to reproduce the behaviour:
Hard to reproduce if you only use github.com, but this is the command I called:
```
GITHUB_URL=https://git.company.com/api/v3/ GITHUB_USER=username GITHUB_TOKEN=token REPOSITORY_CONFIGURATION=orga/repository python3 -m reviews dashboard
```
**Expected behaviour**

Dashboard loads and displays repo

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macos
 - Python Version: 3.9

**Comment by apoclyps** [comment]
@protux could you try and reproduce using `https://git.company.com` without `/api/v3/`?

**Comment by apoclyps** [comment]
may be related to https://github.com/PyGithub/PyGithub/issues/1234

**Comment by apoclyps** [comment]
@protux I've spent some time looking into setting up a trial account for Github Enterprise however there are a number of hurdles to get past. It's unlikely I will be able to reproduce this issue.

I believe the error is bubbling up from the underlying PyGithub library: could you attempt to reproduce the issue with the minimal example provided in their README? see: https://github.com/PyGithub/PyGithub#simple-demo

**Comment by apoclyps** [comment]
I'll leave this issue open for a while in the hopes that a contributor using reviews (with access to Github Enterprise) can test and verify if a fix. If the issue gets stale, I'll drop support for Github Enterprise from reviews as it's not feasible to host/run an instance for this project.

**Comment by protux** [comment]
Hi, I'm sorry, I will try at the beginning of next week. It's still on my TODO. :)

**Comment by apoclyps** [comment]
The `GITHUB_URL` comes from an env var (if provided) and otherwise defaults to `https://api.github.com` if not provided. Adding an env var should allow this to be tested for anyone with a Github Enterprise account.

```bash
export https://api.github.com/api/v3
```

see: https://github.com/apoclyps/reviews/blob/beba9654ca10e6142d183eecc2a81d1c5d6faae6/reviews/config/settings.py#L14

If there is interest in anyone using reviews for a GitHub enterprise, feel free to re-open the issue.
