### ISSUE TITLE
[BUG] Bad/missing credentials are not handled graciously

### ISSUE THREAD

**Issue by jack1142** [apoclyps/reviews#149]
**Describe the bug**
When I try to open the dashboard without first setting proper credentials, I get an ugly traceback:
```
λ reviews dashboard
loading dashboard
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\reviews.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\reviews\cli\main.py", line 54, in main
    cli()
  File "c:\python38\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "c:\python38\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python38\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\reviews\cli\main.py", line 47, in dashboard
    render()
  File "c:\python38\lib\site-packages\reviews\commands.py", line 121, in render
    body=_render_pull_requests(
  File "c:\python38\lib\site-packages\reviews\commands.py", line 39, in _render_pull_requests
    tables = [
  File "c:\python38\lib\site-packages\reviews\commands.py", line 40, in <listcomp>
    controller.retrieve_pull_requests(org=org, repository=repo)
  File "c:\python38\lib\site-packages\reviews\controller.py", line 24, in retrieve_pull_requests
    pull_requests = self.update_pull_requests(org=org, repository=repository)
  File "c:\python38\lib\site-packages\reviews\controller.py", line 57, in update_pull_requests
    pull_requests = self.client.get_pull_requests(org=org, repo=repository)
  File "c:\python38\lib\site-packages\reviews\source_control\client.py", line 39, in get_pull_requests
    repository = self.get_repository(org=org, repo=repo)
  File "c:\python38\lib\site-packages\reviews\source_control\client.py", line 25, in get_repository
    return self._client.get_repo(f"{org}/{repo}")
  File "c:\python38\lib\site-packages\github\MainClass.py", line 330, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "c:\python38\lib\site-packages\github\Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "c:\python38\lib\site-packages\github\Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the latest (0.1.10) version of reviews
2. Run `reviews dashboard`
3. See error.

**Expected behaviour**
A more friendly error message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2004 (OS Build 19041.985)

**Additional context**
N/A

**Comment by apoclyps** [comment]
Thanks for reporting this @jack1142.

I'll reproduce this later this evening when I'm back online and push out a fixed version as soon as possible.

**Comment by apoclyps** [comment]
I've updated this in #151 to display a friendly and helpful error whenever the config is missing or invalid:

![image](https://user-images.githubusercontent.com/1443700/120245065-f604e980-c263-11eb-8c72-a13a7611d6d4.png)

```bash
python -m reviews dashboard --no-reload

GITHUB_TOKEN is required and has not been provided as configuration needed to use Reviews.

> a valid GITHUB_TOKEN should be provided as an environmental variable, or a value within a settings.ini or .env file. Please see the project README for more methods on providing configuration.
```

I'll close out this issue now, but feel free to comment after it's closed if there is anything else you feel should be added or would be helpful to include. I'm always happy to reopen issues (if there is more to add/be done).
